<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>$(LibraryVersionPrefix)</VersionPrefix>
    <AssemblyVersion>$(LibraryAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(LibraryFileVersion)</FileVersion>
  </PropertyGroup>

  <!-- Enable Nullable Reference Types, but only check for warnings on the latest framework -->
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' != '$(LibraryLatestTargetFramework)'">
    <NoWarn>$(NoWarn);nullable</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NeutralLanguage>en-US</NeutralLanguage>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>../../Bin/$(Configuration)/</OutputPath>
    <DocumentationFile>../../Bin/$(Configuration)/$(TargetFramework)/ILGPU.Vulkan.xml</DocumentationFile>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Turn off package validation for now to avoid checks against non-supported frameworks -->
    <EnablePackageValidation>false</EnablePackageValidation>
    <PackageValidationBaselineVersion>$(LibraryPackageValidationBaselineVersion)</PackageValidationBaselineVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Silk.NET.Vulkan" Version="2.22.0" />
    <PackageReference Include="Silk.NET.SPIRV" Version="2.22.0" />
    <PackageReference Include="T4.Build" Version="0.2.5" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ILGPU\ILGPU.csproj" />
  </ItemGroup>

</Project>
