<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Src\ILGPU\ILGPU.csproj" />
    <ProjectReference Include="..\..\Src\ILGPU.Vulkan\ILGPU.Vulkan.csproj" />
  </ItemGroup>
</Project>

